#!/usr/bin/env python3
"""
ai_log_to_data.py

Read the team's AI Log.md and write site/data/ailog.js, the file the Process
section reads its counts from (Module 7).

    python3 scripts/ai_log_to_data.py

What it reads: the first markdown table in AI Log.md whose header row starts
with "Date". Columns are found by their header names (Date, Module, Tool, Task,
Outcome, Verified how, Helped or misled, Logged by), so a team may reorder them.

What it writes: every row as logged, and a summary: rows per module and, for
each module, how many helped, misled, or did not help, read from the start of
the "Helped or misled" cell ("Helped (figures pending verification)" counts as
helped and is also counted as pending).

Standard library only. It never changes AI Log.md.
"""
from __future__ import annotations

import datetime as dt
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOG = ROOT / "AI Log.md"
OUT = ROOT / "site" / "data" / "ailog.js"

KEYS = {  # header text (lowercase, start) -> key
    "date": "date", "module": "module", "tool": "tool", "task": "task", "outcome": "outcome",
    "verified": "verified", "helped": "verdict", "logged": "by",
}


def cells(line: str) -> list[str]:
    line = line.strip()
    if line.startswith("|"):
        line = line[1:]
    if line.endswith("|"):
        line = line[:-1]
    return [c.replace("\\|", "|").strip() for c in re.split(r"(?<!\\)\|", line)]


def verdict_kind(v: str) -> str:
    v = v.strip().lower()
    if v.startswith("misled"):
        return "misled"
    if v.startswith("did not help") or v.startswith("didn't help") or v.startswith("not helpful"):
        return "didNotHelp"
    if v.startswith("helped"):
        return "helped"
    return "other"


def main() -> None:
    if not LOG.exists():
        sys.exit("No AI Log.md at the top of the project.")
    lines = LOG.read_text(encoding="utf-8").splitlines()
    start = next((i for i, l in enumerate(lines) if l.strip().startswith("|") and cells(l)[0].lower() == "date"), None)
    if start is None:
        sys.exit("AI Log.md has no table whose header starts with Date.")
    header = cells(lines[start])
    cols = {}
    for i, h in enumerate(header):
        for prefix, key in KEYS.items():
            if h.lower().startswith(prefix) and key not in cols:
                cols[key] = i
    missing = [k for k in KEYS.values() if k not in cols]

    rows, bad = [], []
    for n, line in enumerate(lines[start + 2:], start + 3):
        if not line.strip().startswith("|"):
            break
        c = cells(line)
        if len(c) < len(header):
            bad.append(n)
            c += [""] * (len(header) - len(c))
        row = {k: c[i] for k, i in cols.items()}
        row["modules"] = [int(m) for m in re.findall(r"\d+", row.get("module", ""))]
        row["kind"] = verdict_kind(row.get("verdict", ""))
        row["pending"] = "pending" in row.get("verdict", "").lower()
        row["line"] = n
        rows.append(row)

    by_module = {}
    for r in rows:
        for m in r["modules"] or [0]:
            b = by_module.setdefault(str(m), {"rows": 0, "helped": 0, "misled": 0, "didNotHelp": 0, "other": 0, "pending": 0})
            b["rows"] += 1
            b[r["kind"]] += 1
            b["pending"] += 1 if r["pending"] else 0
    kinds = {k: sum(1 for r in rows if r["kind"] == k) for k in ("helped", "misled", "didNotHelp", "other")}

    out = {
        "generatedFrom": LOG.name,
        "generatedOn": dt.date.today().isoformat(),
        "rows": rows,
        "summary": {"rows": len(rows), "modules": sorted(int(m) for m in by_module if m != "0"),
                    "byModule": by_module, **kinds, "pending": sum(1 for r in rows if r["pending"])},
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("// Generated by scripts/ai_log_to_data.py from AI Log.md. Do not edit by hand; edit the log and rerun.\n"
                   "window.AILOG = " + json.dumps(out, indent=2, ensure_ascii=False) + ";\n", encoding="utf-8")
    s = out["summary"]
    print(f"Wrote {OUT.relative_to(ROOT)} from {LOG.name}: {s['rows']} rows, modules {s['modules']}")
    print(f"  helped {s['helped']}, misled {s['misled']}, did not help {s['didNotHelp']}, other {s['other']}; pending verification {s['pending']}")
    for m in sorted(by_module, key=int):
        b = by_module[m]
        print(f"  module {m}: {b['rows']} rows (helped {b['helped']}, misled {b['misled']}, did not help {b['didNotHelp']}, other {b['other']})")
    if missing:
        print(f"  columns not found in the header: {', '.join(missing)}")
    if bad:
        print(f"  rows with fewer cells than the header (check their pipes): lines {bad}")
    if "0" in by_module:
        print(f"  {by_module['0']['rows']} rows have no module number")


if __name__ == "__main__":
    main()
